// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./components/AudioPlayer.vue')['default']
    Collection: typeof import('./components/SongFilter/Collection.vue')['default']
    CopyCallCode: typeof import('./components/CopyCallCode.vue')['default']
    CountdownTimer: typeof import('./components/CountdownTimer.vue')['default']
    Credit: typeof import('./components/PopUp/Credit.vue')['default']
    Details: typeof import('./components/PopUp/Details.vue')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ExplainTreated: typeof import('./components/PopUp/ExplainTreated.vue')['default']
    ImportSongList: typeof import('./components/ImportSongList.vue')['default']
    Info: typeof import('./components/PopUp/Info.vue')['default']
    LoadingPanel: typeof import('./components/LoadingPanel.vue')['default']
    Main: typeof import('./components/PopUp/Main.vue')['default']
    MainSongList: typeof import('./components/MainSongList.vue')['default']
    MyCollection: typeof import('./components/SongFilter/MyCollection.vue')['default']
    PageBanner: typeof import('./components/PageBanner.vue')['default']
    PageFooter: typeof import('./components/PageFooter.vue')['default']
    PlayList: typeof import('./components/PlayList.vue')['default']
    PlayListItem: typeof import('./components/PlayListItem.vue')['default']
    Receive: typeof import('./components/PopUp/Receive.vue')['default']
    Share: typeof import('./components/PopUp/Share.vue')['default']
    SongListPagination: typeof import('./components/SongListPagination.vue')['default']
  }
}
